/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-10-23 09:45:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.config;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.net.URL;
import java.net.MalformedURLException;
import java.io.FileReader;
import java.util.Properties;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.net.MalformedURLException");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.io.FileReader");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // extract variables for easier development.
    // for eclipse development you will have to replace webapps with wtpwebapps
    String contextName = "oxygen-xml-web-author";
    boolean isRedirectEnabled = true;
    
      
    if (isRedirectEnabled && "activated".equals(System.getProperty("com.oxygenxml.license.server.state"))) {
      response.sendRedirect("/" + contextName + "/app/oxygen.html");
      return;
    }

   File catalinaBase = new File(System.getProperty("catalina.base"));
   // If web author does not use the builtin server, skip this configuration page.
    Properties p = new Properties();
    FileReader fr = null;
    try{
      try {
        fr = new FileReader(new File(catalinaBase, "work/Catalina/localhost/" + contextName + "/options/license.properties"));
        p.load(fr);
      } finally {
        if (fr != null) {
          fr.close();
        }
      }
    } catch (IOException e) {
      // Ignore the error.
    }

    String licenseServerStr = p.getProperty("licensing.server.url");
    URL licenseServerUrl = null;
    try {
      licenseServerUrl = new URL(licenseServerStr);
    } catch (MalformedURLException e) {
      // Ignore the error.
    }

    if (isRedirectEnabled && (licenseServerUrl == null || !"localhost".equals(licenseServerUrl.getHost()))) {
      response.sendRedirect("/" + contextName + "/app/oxygen.html");
      return;
    }

    // Determine the name of the css file which contains a hashcode.
    File cssFolder = new File(catalinaBase, "webapps/" + contextName + "/app/css");
    String[] cssFiles = cssFolder.list(new FilenameFilter() {
      public boolean accept(File dir, String name) {
        return name.startsWith("admin-page-");
      }
    });
    String adminCss = cssFiles[0];


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- No zoom. -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicons -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"/");
      out.print( contextName );
      out.write("/app/images/gui/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <title>Oxygen XML Web Author Configuration Page</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"layout.css?cache-id=");
      out.print(System.getProperty("com.oxygenxml.webapp.version"));
      out.write("\" />\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/");
      out.print( contextName );
      out.write("/app/css/");
      out.print( adminCss );
      out.write("\" />\r\n");
      out.write("    <script src=\"/");
      out.print( contextName );
      out.write("/app/");
      out.print( System.getProperty("com.oxygenxml.webapp.version") );
      out.write("-node_modules/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"webapp-admin-page\">\r\n");
      out.write("        <div id=\"header-bar\" class=\"ui-layout-north\">\r\n");
      out.write("            <div class=\"header-left vertical-align-children\">\r\n");
      out.write("                <a  href=\"/");
      out.print(  contextName );
      out.write("/app/oxygen.html\" title=\"Go to Oxygen XML Web Author Dashboard\" \r\n");
      out.write("					id=\"header-logo\" class=\"vertical-align-children\">\r\n");
      out.write("                	<div class=\"large-logo logo-container vertical-align-children\">\r\n");
      out.write("                    	<div class=\"ui-oxygen-logo\"></div>\r\n");
      out.write("                	</div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <span>Configuration Page</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"section-title\">\r\n");
      out.write("            <div class=\"title\">License configuration</div>\r\n");
      out.write("            \r\n");
      out.write("            <p>Oxygen XML Web Author is installed. In order to use it, you need to connect it to an \r\n");
      out.write("              Oxygen License Server that serves an Oxygen floating license key.</p>\r\n");
      out.write("\r\n");
      out.write("            <p>Choose one of the options below:</p>\r\n");
      out.write("            <div class=\"options\">\r\n");
      out.write("\r\n");
      out.write("              <div id=\"trial\" class=\"option\">\r\n");
      out.write("                <div class=\"preview\">\r\n");
      out.write("                  <div class=\"title\">Trial</div>\r\n");
      out.write("                  <div class=\"shortdesc\">You can try Oxygen XML Web Author for 30 days. No setup required.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"details\">\r\n");
      out.write("                  <div class=\"form ihave\">\r\n");
      out.write("                    <div class=\"tabs\"> \r\n");
      out.write("                      <div class=\"trial-option option-selected\">Request a trial license</div>\r\n");
      out.write("                      <div class=\"trial-option option-not-selected\">I already have a trial license</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"ihave\">\r\n");
      out.write("                    <div style=\"margin:15px 0\">Please fill-in the form below to start your trial.</div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-4 text-right label\"><label for=\"email\">Email<span class=\"red\">*</span></label></div>\r\n");
      out.write("                    <div class=\"col-md-4\"><input type=\"email\" name=\"email\" id=\"email\" value=\"\" class=\"required form-control\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-4 text-right label\"><label for=\"name\">Name</label></div>\r\n");
      out.write("                    <div class=\"col-md-4\"><input type=\"text\" id=\"name\" name=\"name\" value=\"\" class=\"form-control\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-4 text-right label\"><label for=\"company\">Company</label></div>\r\n");
      out.write("                    <div class=\"col-md-4\"><input type=\"text\" name=\"company\" id=\"company\" value=\"\" class=\"form-control\"></div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-md-4 text-right\"><label for=\"country\">Country<span class=\"red\">*</span></label></div>\r\n");
      out.write("                    <div class=\"col-md-4\"><select name=\"country\" id=\"country\" class=\"form-control required\">\r\n");
      out.write("                        <option value=\"\">-- Select --</option>\r\n");
      out.write("                        <option value=\"Afganistan\">Afghanistan</option>\r\n");
      out.write("                        <option value=\"Albania\">Albania</option>\r\n");
      out.write("                        <option value=\"Algeria\">Algeria</option>\r\n");
      out.write("                        <option value=\"American Samoa\">American Samoa</option>\r\n");
      out.write("                        <option value=\"Andorra\">Andorra</option>\r\n");
      out.write("                        <option value=\"Angola\">Angola</option>\r\n");
      out.write("                        <option value=\"Anguilla\">Anguilla</option>\r\n");
      out.write("                        <option value=\"Antigua &amp; Barbuda\">Antigua &amp; Barbuda</option>\r\n");
      out.write("                        <option value=\"Argentina\">Argentina</option>\r\n");
      out.write("                        <option value=\"Armenia\">Armenia</option>\r\n");
      out.write("                        <option value=\"Aruba\">Aruba</option>\r\n");
      out.write("                        <option value=\"Australia\">Australia</option>\r\n");
      out.write("                        <option value=\"Austria\">Austria</option>\r\n");
      out.write("                        <option value=\"Azerbaijan\">Azerbaijan</option>\r\n");
      out.write("                        <option value=\"Bahamas\">Bahamas</option>\r\n");
      out.write("                        <option value=\"Bahrain\">Bahrain</option>\r\n");
      out.write("                        <option value=\"Bangladesh\">Bangladesh</option>\r\n");
      out.write("                        <option value=\"Barbados\">Barbados</option>\r\n");
      out.write("                        <option value=\"Belarus\">Belarus</option>\r\n");
      out.write("                        <option value=\"Belgium\">Belgium</option>\r\n");
      out.write("                        <option value=\"Belize\">Belize</option>\r\n");
      out.write("                        <option value=\"Benin\">Benin</option>\r\n");
      out.write("                        <option value=\"Bermuda\">Bermuda</option>\r\n");
      out.write("                        <option value=\"Bhutan\">Bhutan</option>\r\n");
      out.write("                        <option value=\"Bolivia\">Bolivia</option>\r\n");
      out.write("                        <option value=\"Bonaire\">Bonaire</option>\r\n");
      out.write("                        <option value=\"Bosnia &amp; Herzegovina\">Bosnia &amp; Herzegovina</option>\r\n");
      out.write("                        <option value=\"Botswana\">Botswana</option>\r\n");
      out.write("                        <option value=\"Brazil\">Brazil</option>\r\n");
      out.write("                        <option value=\"British Indian Ocean Ter\">British Indian Ocean Ter</option>\r\n");
      out.write("                        <option value=\"Brunei\">Brunei</option>\r\n");
      out.write("                        <option value=\"Bulgaria\">Bulgaria</option>\r\n");
      out.write("                        <option value=\"Burkina Faso\">Burkina Faso</option>\r\n");
      out.write("                        <option value=\"Burundi\">Burundi</option>\r\n");
      out.write("                        <option value=\"Cambodia\">Cambodia</option>\r\n");
      out.write("                        <option value=\"Cameroon\">Cameroon</option>\r\n");
      out.write("                        <option value=\"Canada\">Canada</option>\r\n");
      out.write("                        <option value=\"Canary Islands\">Canary Islands</option>\r\n");
      out.write("                        <option value=\"Cape Verde\">Cape Verde</option>\r\n");
      out.write("                        <option value=\"Cayman Islands\">Cayman Islands</option>\r\n");
      out.write("                        <option value=\"Central African Republic\">Central African Republic</option>\r\n");
      out.write("                        <option value=\"Chad\">Chad</option>\r\n");
      out.write("                        <option value=\"Channel Islands\">Channel Islands</option>\r\n");
      out.write("                        <option value=\"Chile\">Chile</option>\r\n");
      out.write("                        <option value=\"China\">China</option>\r\n");
      out.write("                        <option value=\"Christmas Island\">Christmas Island</option>\r\n");
      out.write("                        <option value=\"Cocos Island\">Cocos Island</option>\r\n");
      out.write("                        <option value=\"Colombia\">Colombia</option>\r\n");
      out.write("                        <option value=\"Comoros\">Comoros</option>\r\n");
      out.write("                        <option value=\"Congo\">Congo</option>\r\n");
      out.write("                        <option value=\"Cook Islands\">Cook Islands</option>\r\n");
      out.write("                        <option value=\"Costa Rica\">Costa Rica</option>\r\n");
      out.write("                        <option value=\"Cote DIvoire\">Cote D'Ivoire</option>\r\n");
      out.write("                        <option value=\"Croatia\">Croatia</option>\r\n");
      out.write("                        <option value=\"Cuba\">Cuba</option>\r\n");
      out.write("                        <option value=\"Curaco\">Curacao</option>\r\n");
      out.write("                        <option value=\"Cyprus\">Cyprus</option>\r\n");
      out.write("                        <option value=\"Czech Republic\">Czech Republic</option>\r\n");
      out.write("                        <option value=\"Denmark\">Denmark</option>\r\n");
      out.write("                        <option value=\"Djibouti\">Djibouti</option>\r\n");
      out.write("                        <option value=\"Dominica\">Dominica</option>\r\n");
      out.write("                        <option value=\"Dominican Republic\">Dominican Republic</option>\r\n");
      out.write("                        <option value=\"East Timor\">East Timor</option>\r\n");
      out.write("                        <option value=\"Ecuador\">Ecuador</option>\r\n");
      out.write("                        <option value=\"Egypt\">Egypt</option>\r\n");
      out.write("                        <option value=\"El Salvador\">El Salvador</option>\r\n");
      out.write("                        <option value=\"Equatorial Guinea\">Equatorial Guinea</option>\r\n");
      out.write("                        <option value=\"Eritrea\">Eritrea</option>\r\n");
      out.write("                        <option value=\"Estonia\">Estonia</option>\r\n");
      out.write("                        <option value=\"Ethiopia\">Ethiopia</option>\r\n");
      out.write("                        <option value=\"Falkland Islands\">Falkland Islands</option>\r\n");
      out.write("                        <option value=\"Faroe Islands\">Faroe Islands</option>\r\n");
      out.write("                        <option value=\"Fiji\">Fiji</option>\r\n");
      out.write("                        <option value=\"Finland\">Finland</option>\r\n");
      out.write("                        <option value=\"France\">France</option>\r\n");
      out.write("                        <option value=\"French Guiana\">French Guiana</option>\r\n");
      out.write("                        <option value=\"French Polynesia\">French Polynesia</option>\r\n");
      out.write("                        <option value=\"French Southern Ter\">French Southern Ter</option>\r\n");
      out.write("                        <option value=\"Gabon\">Gabon</option>\r\n");
      out.write("                        <option value=\"Gambia\">Gambia</option>\r\n");
      out.write("                        <option value=\"Georgia\">Georgia</option>\r\n");
      out.write("                        <option value=\"Germany\">Germany</option>\r\n");
      out.write("                        <option value=\"Ghana\">Ghana</option>\r\n");
      out.write("                        <option value=\"Gibraltar\">Gibraltar</option>\r\n");
      out.write("                        <option value=\"Great Britain\">Great Britain</option>\r\n");
      out.write("                        <option value=\"Greece\">Greece</option>\r\n");
      out.write("                        <option value=\"Greenland\">Greenland</option>\r\n");
      out.write("                        <option value=\"Grenada\">Grenada</option>\r\n");
      out.write("                        <option value=\"Guadeloupe\">Guadeloupe</option>\r\n");
      out.write("                        <option value=\"Guam\">Guam</option>\r\n");
      out.write("                        <option value=\"Guatemala\">Guatemala</option>\r\n");
      out.write("                        <option value=\"Guinea\">Guinea</option>\r\n");
      out.write("                        <option value=\"Guyana\">Guyana</option>\r\n");
      out.write("                        <option value=\"Haiti\">Haiti</option>\r\n");
      out.write("                        <option value=\"Hawaii\">Hawaii</option>\r\n");
      out.write("                        <option value=\"Honduras\">Honduras</option>\r\n");
      out.write("                        <option value=\"Hong Kong\">Hong Kong</option>\r\n");
      out.write("                        <option value=\"Hungary\">Hungary</option>\r\n");
      out.write("                        <option value=\"Iceland\">Iceland</option>\r\n");
      out.write("                        <option value=\"India\">India</option>\r\n");
      out.write("                        <option value=\"Indonesia\">Indonesia</option>\r\n");
      out.write("                        <option value=\"Iran\">Iran</option>\r\n");
      out.write("                        <option value=\"Iraq\">Iraq</option>\r\n");
      out.write("                        <option value=\"Ireland\">Ireland</option>\r\n");
      out.write("                        <option value=\"Isle of Man\">Isle of Man</option>\r\n");
      out.write("                        <option value=\"Israel\">Israel</option>\r\n");
      out.write("                        <option value=\"Italy\">Italy</option>\r\n");
      out.write("                        <option value=\"Jamaica\">Jamaica</option>\r\n");
      out.write("                        <option value=\"Japan\">Japan</option>\r\n");
      out.write("                        <option value=\"Jordan\">Jordan</option>\r\n");
      out.write("                        <option value=\"Kazakhstan\">Kazakhstan</option>\r\n");
      out.write("                        <option value=\"Kenya\">Kenya</option>\r\n");
      out.write("                        <option value=\"Kiribati\">Kiribati</option>\r\n");
      out.write("                        <option value=\"Korea North\">Korea North</option>\r\n");
      out.write("                        <option value=\"Korea Sout\">Korea South</option>\r\n");
      out.write("                        <option value=\"Kuwait\">Kuwait</option>\r\n");
      out.write("                        <option value=\"Kyrgyzstan\">Kyrgyzstan</option>\r\n");
      out.write("                        <option value=\"Laos\">Laos</option>\r\n");
      out.write("                        <option value=\"Latvia\">Latvia</option>\r\n");
      out.write("                        <option value=\"Lebanon\">Lebanon</option>\r\n");
      out.write("                        <option value=\"Lesotho\">Lesotho</option>\r\n");
      out.write("                        <option value=\"Liberia\">Liberia</option>\r\n");
      out.write("                        <option value=\"Libya\">Libya</option>\r\n");
      out.write("                        <option value=\"Liechtenstein\">Liechtenstein</option>\r\n");
      out.write("                        <option value=\"Lithuania\">Lithuania</option>\r\n");
      out.write("                        <option value=\"Luxembourg\">Luxembourg</option>\r\n");
      out.write("                        <option value=\"Macau\">Macau</option>\r\n");
      out.write("                        <option value=\"Macedonia\">Macedonia</option>\r\n");
      out.write("                        <option value=\"Madagascar\">Madagascar</option>\r\n");
      out.write("                        <option value=\"Malaysia\">Malaysia</option>\r\n");
      out.write("                        <option value=\"Malawi\">Malawi</option>\r\n");
      out.write("                        <option value=\"Maldives\">Maldives</option>\r\n");
      out.write("                        <option value=\"Mali\">Mali</option>\r\n");
      out.write("                        <option value=\"Malta\">Malta</option>\r\n");
      out.write("                        <option value=\"Marshall Islands\">Marshall Islands</option>\r\n");
      out.write("                        <option value=\"Martinique\">Martinique</option>\r\n");
      out.write("                        <option value=\"Mauritania\">Mauritania</option>\r\n");
      out.write("                        <option value=\"Mauritius\">Mauritius</option>\r\n");
      out.write("                        <option value=\"Mayotte\">Mayotte</option>\r\n");
      out.write("                        <option value=\"Mexico\">Mexico</option>\r\n");
      out.write("                        <option value=\"Midway Islands\">Midway Islands</option>\r\n");
      out.write("                        <option value=\"Moldova\">Moldova</option>\r\n");
      out.write("                        <option value=\"Monaco\">Monaco</option>\r\n");
      out.write("                        <option value=\"Mongolia\">Mongolia</option>\r\n");
      out.write("                        <option value=\"Montserrat\">Montserrat</option>\r\n");
      out.write("                        <option value=\"Morocco\">Morocco</option>\r\n");
      out.write("                        <option value=\"Mozambique\">Mozambique</option>\r\n");
      out.write("                        <option value=\"Myanmar\">Myanmar</option>\r\n");
      out.write("                        <option value=\"Nambia\">Nambia</option>\r\n");
      out.write("                        <option value=\"Nauru\">Nauru</option>\r\n");
      out.write("                        <option value=\"Nepal\">Nepal</option>\r\n");
      out.write("                        <option value=\"Netherland Antilles\">Netherland Antilles</option>\r\n");
      out.write("                        <option value=\"Netherlands\">Netherlands</option>\r\n");
      out.write("                        <option value=\"Nevis\">Nevis</option>\r\n");
      out.write("                        <option value=\"New Caledonia\">New Caledonia</option>\r\n");
      out.write("                        <option value=\"New Zealand\">New Zealand</option>\r\n");
      out.write("                        <option value=\"Nicaragua\">Nicaragua</option>\r\n");
      out.write("                        <option value=\"Niger\">Niger</option>\r\n");
      out.write("                        <option value=\"Nigeria\">Nigeria</option>\r\n");
      out.write("                        <option value=\"Niue\">Niue</option>\r\n");
      out.write("                        <option value=\"Norfolk Island\">Norfolk Island</option>\r\n");
      out.write("                        <option value=\"Norway\">Norway</option>\r\n");
      out.write("                        <option value=\"Oman\">Oman</option>\r\n");
      out.write("                        <option value=\"Pakistan\">Pakistan</option>\r\n");
      out.write("                        <option value=\"Palau Island\">Palau Island</option>\r\n");
      out.write("                        <option value=\"Palestine\">Palestine</option>\r\n");
      out.write("                        <option value=\"Panama\">Panama</option>\r\n");
      out.write("                        <option value=\"Papua New Guinea\">Papua New Guinea</option>\r\n");
      out.write("                        <option value=\"Paraguay\">Paraguay</option>\r\n");
      out.write("                        <option value=\"Peru\">Peru</option>\r\n");
      out.write("                        <option value=\"Phillipines\">Philippines</option>\r\n");
      out.write("                        <option value=\"Pitcairn Island\">Pitcairn Island</option>\r\n");
      out.write("                        <option value=\"Poland\">Poland</option>\r\n");
      out.write("                        <option value=\"Portugal\">Portugal</option>\r\n");
      out.write("                        <option value=\"Puerto Rico\">Puerto Rico</option>\r\n");
      out.write("                        <option value=\"Qatar\">Qatar</option>\r\n");
      out.write("                        <option value=\"Reunion\">Reunion</option>\r\n");
      out.write("                        <option value=\"Romania\">Romania</option>\r\n");
      out.write("                        <option value=\"Russia\">Russia</option>\r\n");
      out.write("                        <option value=\"Rwanda\">Rwanda</option>\r\n");
      out.write("                        <option value=\"St Barthelemy\">St Barthelemy</option>\r\n");
      out.write("                        <option value=\"St Eustatius\">St Eustatius</option>\r\n");
      out.write("                        <option value=\"St Helena\">St Helena</option>\r\n");
      out.write("                        <option value=\"St Kitts-Nevis\">St Kitts-Nevis</option>\r\n");
      out.write("                        <option value=\"St Lucia\">St Lucia</option>\r\n");
      out.write("                        <option value=\"St Maarten\">St Maarten</option>\r\n");
      out.write("                        <option value=\"St Pierre &amp; Miquelon\">St Pierre &amp; Miquelon</option>\r\n");
      out.write("                        <option value=\"St Vincent &amp; Grenadines\">St Vincent &amp; Grenadines</option>\r\n");
      out.write("                        <option value=\"Saipan\">Saipan</option>\r\n");
      out.write("                        <option value=\"Samoa\">Samoa</option>\r\n");
      out.write("                        <option value=\"Samoa American\">Samoa American</option>\r\n");
      out.write("                        <option value=\"San Marino\">San Marino</option>\r\n");
      out.write("                        <option value=\"Sao Tome &amp; Principe\">Sao Tome &amp; Principe</option>\r\n");
      out.write("                        <option value=\"Saudi Arabia\">Saudi Arabia</option>\r\n");
      out.write("                        <option value=\"Senegal\">Senegal</option>\r\n");
      out.write("                        <option value=\"Seychelles\">Seychelles</option>\r\n");
      out.write("                        <option value=\"Serbia &amp; Montenegro\">Serbia &amp; Montenegro</option>\r\n");
      out.write("                        <option value=\"Sierra Leone\">Sierra Leone</option>\r\n");
      out.write("                        <option value=\"Singapore\">Singapore</option>\r\n");
      out.write("                        <option value=\"Slovakia\">Slovakia</option>\r\n");
      out.write("                        <option value=\"Slovenia\">Slovenia</option>\r\n");
      out.write("                        <option value=\"Solomon Islands\">Solomon Islands</option>\r\n");
      out.write("                        <option value=\"Somalia\">Somalia</option>\r\n");
      out.write("                        <option value=\"South Africa\">South Africa</option>\r\n");
      out.write("                        <option value=\"Spain\">Spain</option>\r\n");
      out.write("                        <option value=\"Sri Lanka\">Sri Lanka</option>\r\n");
      out.write("                        <option value=\"Sudan\">Sudan</option>\r\n");
      out.write("                        <option value=\"Suriname\">Suriname</option>\r\n");
      out.write("                        <option value=\"Swaziland\">Swaziland</option>\r\n");
      out.write("                        <option value=\"Sweden\">Sweden</option>\r\n");
      out.write("                        <option value=\"Switzerland\">Switzerland</option>\r\n");
      out.write("                        <option value=\"Syria\">Syria</option>\r\n");
      out.write("                        <option value=\"Tahiti\">Tahiti</option>\r\n");
      out.write("                        <option value=\"Taiwan\">Taiwan</option>\r\n");
      out.write("                        <option value=\"Tajikistan\">Tajikistan</option>\r\n");
      out.write("                        <option value=\"Tanzania\">Tanzania</option>\r\n");
      out.write("                        <option value=\"Thailand\">Thailand</option>\r\n");
      out.write("                        <option value=\"Togo\">Togo</option>\r\n");
      out.write("                        <option value=\"Tokelau\">Tokelau</option>\r\n");
      out.write("                        <option value=\"Tonga\">Tonga</option>\r\n");
      out.write("                        <option value=\"Trinidad &amp; Tobago\">Trinidad &amp; Tobago</option>\r\n");
      out.write("                        <option value=\"Tunisia\">Tunisia</option>\r\n");
      out.write("                        <option value=\"Turkey\">Turkey</option>\r\n");
      out.write("                        <option value=\"Turkmenistan\">Turkmenistan</option>\r\n");
      out.write("                        <option value=\"Turks &amp; Caicos Is\">Turks &amp; Caicos Is</option>\r\n");
      out.write("                        <option value=\"Tuvalu\">Tuvalu</option>\r\n");
      out.write("                        <option value=\"Uganda\">Uganda</option>\r\n");
      out.write("                        <option value=\"Ukraine\">Ukraine</option>\r\n");
      out.write("                        <option value=\"United Arab Erimates\">United Arab Emirates</option>\r\n");
      out.write("                        <option value=\"United Kingdom\">United Kingdom</option>\r\n");
      out.write("                        <option value=\"United States of America\">United States of America</option>\r\n");
      out.write("                        <option value=\"Uraguay\">Uruguay</option>\r\n");
      out.write("                        <option value=\"Uzbekistan\">Uzbekistan</option>\r\n");
      out.write("                        <option value=\"Vanuatu\">Vanuatu</option>\r\n");
      out.write("                        <option value=\"Vatican City State\">Vatican City State</option>\r\n");
      out.write("                        <option value=\"Venezuela\">Venezuela</option>\r\n");
      out.write("                        <option value=\"Vietnam\">Vietnam</option>\r\n");
      out.write("                        <option value=\"Virgin Islands (Brit)\">Virgin Islands (Brit)</option>\r\n");
      out.write("                        <option value=\"Virgin Islands (USA)\">Virgin Islands (USA)</option>\r\n");
      out.write("                        <option value=\"Wake Island\">Wake Island</option>\r\n");
      out.write("                        <option value=\"Wallis &amp; Futana Is\">Wallis &amp; Futana Is</option>\r\n");
      out.write("                        <option value=\"Yemen\">Yemen</option>\r\n");
      out.write("                        <option value=\"Zaire\">Zaire</option>\r\n");
      out.write("                        <option value=\"Zambia\">Zambia</option>\r\n");
      out.write("                        <option value=\"Zimbabwe\">Zimbabwe</option>\r\n");
      out.write("                    </select></div>\r\n");
      out.write("                      <div id=\"email-consent\">\r\n");
      out.write("                        <div>Choose the types of notifications you want to receive:</div>\r\n");
      out.write("                        <div> <label><input id=\"subscribe_newrelease\" name=\"subscribe_newrelease\" type=\"checkbox\">Oxygen Web Author release announcements and subscription/SMP renewal notifications</label></div>\r\n");
      out.write("                        <div> <label><input id=\"subscribe_newsletter\" name=\"subscribe_newsletter\" type=\"checkbox\">Oxygen Web Author-related events, such as webinars, demos, and conferences</label></div>                        \r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div style=\"margin-left: 25%;\">The personal information requested is used for no other purposes than to keep connected with you regarding Oxygen Web Author updates.</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"idonthave\">\r\n");
      out.write("                      <div class=\"col-md-2\"></div>\r\n");
      out.write("                      <div class=\"col-md-8\">Paste your Oxygen XML Web Author license key<span class=\"red\">*</span></div>\r\n");
      out.write("                      <div class=\"col-md-2\"></div>\r\n");
      out.write("                      <textarea id=\"pasted-license\" class=\"col-md-8\" rows=\"9\"></textarea>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                      <button id=\"get-trial\" class=\"oxy-button oxy-button--primary\">Start Trial</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"result\">\r\n");
      out.write("                    <div class=\"loading text-center\">\r\n");
      out.write("                      Activating your trial key...\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"success text-center\">\r\n");
      out.write("                      <div style=\"margin:15px 0\">Your trial key was activated.</div>\r\n");
      out.write("                      <a class=\"oxy-button oxy-button--primary\" href=\"/");
      out.print( contextName );
      out.write("/app/oxygen.html\" >Go to Dashboard</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"failure\">\r\n");
      out.write("                      Failed to use a trial license key.\r\n");
      out.write("                      <div>\r\n");
      out.write("                      You can go to Oxygen XML Web Author <a href=\"https://www.oxygenxml.com/webauthor/\">web page</a> to get a license\r\n");
      out.write("                      and activate it on the <a href=\"/license-servlet\">builtin license server</a>.\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("              <div id=\"simple\" class=\"option\">\r\n");
      out.write("                <div class=\"preview\">\r\n");
      out.write("                  <div class=\"title\">Fast setup</div>\r\n");
      out.write("                  <div class=\"shortdesc\">The simplest way to start using the Oxygen XML Web Author with a commercial license.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"details\">A floating license server was already installed together with Oxygen XML Web Author.\r\n");
      out.write("                Go to the floating license server setup page to activate your license key.\r\n");
      out.write("                  <div class=\"text-center\">\r\n");
      out.write("                    <a href=\"/license-servlet/\" class=\"oxy-button oxy-button--primary\">License server setup page</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div id=\"advanced\" class=\"option\">\r\n");
      out.write("                <div class=\"preview\">\r\n");
      out.write("                  <div class=\"title\">Flexible setup</div>\r\n");
      out.write("                  <div class=\"shortdesc\">Involves setting up the license server on a dedicated machine. This gives you increased \r\n");
      out.write("                    flexibility for more complex deployments.</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"details\">Instructions:\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>Install an external license server. You can download it <a href=\"https://www.oxygenxml.com/license_server.html\">here</a>.\r\n");
      out.write("                    <li>Activate your license key with the newly installed license server.\r\n");
      out.write("                    <li>Connect Oxygen XML Web Author to the newly installed license server using the \r\n");
      out.write("                      <a href=\"/");
      out.print( contextName );
      out.write("/app/admin.html#License\">Administration Page</a>. \r\n");
      out.write("                    <li><a href=\"/");
      out.print( contextName );
      out.write("/app/oxygen.html\">Go to dashboard</a>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"config.js?cache-id=");
      out.print(System.getProperty("com.oxygenxml.webapp.version"));
      out.write("\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
